services:
  uit-wiki:
    container_name: uit-wiki
    image: uit-wiki
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - REDIS_HOST=redis 
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'